import { useState } from "react";
import { useNavigate } from "react-router-dom";
import ReactMarkdown from "react-markdown";
import { motion, AnimatePresence } from "framer-motion";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import toast from "react-hot-toast";
import TravelChecklist from "./TravelChecklist";
import TravelTips from "./TravelTips";
import { useAuthStore } from "../stores/authStore";
import { communityService } from "../services/communityService";
import "../styles/scheduledetail.css";

export default function ScheduleDetailView({ schedule }) {
    const { user } = useAuthStore();
    const navigate = useNavigate();
    
    if (!schedule) {
        return <div style={{ padding: '2rem', textAlign: 'center' }}>일정 정보를 불러올 수 없습니다.</div>;
    }
    const [activeDay, setActiveDay] = useState(1);
    const [expandedItems, setExpandedItems] = useState({});
    const [activeSection, setActiveSection] = useState("timeline"); // timeline, checklist, tips
    const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);
    const [showShareConfirm, setShowShareConfirm] = useState(false);
    const [showShareSuccess, setShowShareSuccess] = useState(false);
    const [isSharing, setIsSharing] = useState(false); // Double-submission prevention
    const [currentChecklist, setCurrentChecklist] = useState([]);

    const handleChecklistChange = (newChecklist) => {
        setCurrentChecklist(newChecklist);
    };

    // Parse schedule text into day-separated data
    const parseDailySchedule = (text) => {
        if (!text || typeof text !== 'string') {
            return [];
        }

        // 1. Try JSON Parsing first (for AI Generated Schedules)
        try {
            const parsed = JSON.parse(text);
            if (Array.isArray(parsed)) {
                return parsed.map(day => ({
                    day: day.day,
                    items: (day.spots || day.items || []).map(spot => ({
                        time: spot.time || "00:00",
                        emoji: spot.emoji || "📍",
                        title: spot.spot || spot.title || "장소",
                        description: spot.activity || spot.description || "",
                        category: spot.category || "기타",
                        cost: spot.cost || 0,
                        costDescription: spot.costDescription || ""
                    }))
                }));
            }
        } catch (e) {
            // Not JSON, continue to text parsing
        }

        // 2. Fallback to Text Parsing (Robust Regex)
        try {
            const daySplitRegex = /\[Day (\d+)\]|## (\d+)일차|(\d+)일차:/g;
            const matches = [...text.matchAll(daySplitRegex)];
            
            if (matches.length === 0) return [];

            const legacyDays = matches.map((match, idx) => {
                const dayNum = parseInt(match[1] || match[2] || match[3]);
                const nextMatch = matches[idx + 1];
                const start = match.index + match[0].length;
                const end = nextMatch ? nextMatch.index : text.length;
                const block = text.slice(start, end).trim();
                
                const lines = block.split("\n").filter(line => line.trim());
                const items = [];
                let currentItem = null;

                for (let i = 0; i < lines.length; i++) {
                    const line = lines[i].trim();
                    // Matches formats: 
                    // 1. "09:00 - 🌅 Place" (Legacy)
                    // 2. "- [09:00] Place 🌅 : Activity" (Markdown generated by AI)
                    
                    const legacyMatch = line.match(/^(\d{2}:\d{2})\s*[-–]\s*(.+)/);
                    const mdMatch = line.match(/^- \s*\[(\d{2}:\d{2})\]\s*(.+?)\s*([^\s:]+)?\s*:\s*(.+)/);
                    // Match cost line if generic markdown parsing added it? E.g. "  - 5,000"
                    // For now, regex parsing ignores cost. JSON is preferred.

                    if (legacyMatch || mdMatch) {
                         if (currentItem) items.push(currentItem);
                         
                         if (mdMatch) {
                             const [_, time, title, emoji, desc] = mdMatch;
                             currentItem = {
                                 time,
                                 emoji: emoji || "📍",
                                 title: title.trim(),
                                 description: desc.trim(),
                                 category: getCategoryFromEmoji(emoji || "📍"),
                                 cost: 0 // No parsing for markdown currently
                             };
                         } else {
                             const [_, time, content] = legacyMatch;
                             const emojiMatch = content.match(/^([^\s]+)\s+(.+)/);
                             currentItem = {
                                 time,
                                 emoji: emojiMatch ? emojiMatch[1] : "📍",
                                 title: emojiMatch ? emojiMatch[2] : content,
                                 description: "",
                                 category: getCategoryFromEmoji(emojiMatch ? emojiMatch[1] : "📍"),
                                 cost: 0
                             };
                         }
                    } else if (currentItem && line) {
                        currentItem.description += (currentItem.description ? " " : "") + line;
                    }
                }
                if (currentItem) items.push(currentItem);
                return { day: dayNum, items };
            });

            return legacyDays.filter(d => d.items.length > 0);
        } catch (error) {
            console.error("Schedule parsing error:", error);
            return [];
        }
    };

    const getCategoryFromEmoji = (emoji) => {
        const categories = {
            "🌅": "자연",
            "☕": "카페",
            "🚴": "액티비티",
            "🌲": "자연",
            "🍰": "음식",
            "💆": "휴식",
            "✨": "관광",
            "🌊": "해변",
            "🦞": "맛집",
            "🎨": "문화",
            "🌉": "야경",
            "🏯": "관광",
            "🍵": "카페",
            "🗼": "관광",
            "🐟": "맛집",
            "🥞": "음식",
            "🍻": "식당",
            "🥘": "맛집",
            "🍜": "맛집",
            "🍝": "맛집",
            "🦐": "맛집",
            "⛰️": "액티비티",
            "🕳️": "액티비티",
            "🏄": "액티비티",
            "😴": "휴식",
            "🧘": "휴식",
            "🕉️": "휴식",
            "🎵": "문화",
            "♨️": "휴식",
            "📚": "문화",
            "🎬": "문화",
            "🌺": "자연",
            "🍱": "음식",
            "💧": "자연",
            "🍖": "맛집",
            "🛍️": "쇼핑",
            "🚣": "액티비티",
            "🏖️": "해변",
            "🥗": "음식",
            "🥑": "음식",
            "🥾": "액티비티",
            "🗼": "관광",
            "🏐": "액티비티",
            "🍔": "맛집",
            "🏃": "액티비티",
            "🥐": "음식",
            "🍶": "음식",
            "🥩": "맛집",
            "🍲": "맛집",
            "🍢": "맛집",
            "🍡": "음식",
            "🏛️": "문화",
            "🥁": "문화",
            "🌳": "자연",
            "🏢": "관광",
            "✈️": "관광",
        };
        return categories[emoji] || "기타";
    };
    const toggleExpand = (dayIndex, itemIndex) => {
        const key = `${dayIndex}-${itemIndex}`;
        setExpandedItems(prev => ({
            ...prev,
            [key]: !prev[key]
        }));
    };


    // PDF 생성 함수 (html2canvas 사용)
    const generatePDF = async () => {
        if (isGeneratingPDF) return;

        toast.dismiss(); // 기존 토스트들 모두 닫기 (PDF 캡처에 방해되지 않도록)
        setIsGeneratingPDF(true);
        const toastId = toast.loading("PDF 만드는 중이에요...");

        try {
            // PDF용 임시 컨테이너 생성
            const pdfContainer = document.createElement('div');
            // 9999px left is fine, but we need it to be visible enough for html2canvas to work correctly in some browsers
            pdfContainer.style.cssText = `
                position: absolute;
                left: -9999px;
                top: 0;
                width: 175mm;
                background: white;
                font-family: 'Malgun Gothic', '맑은 고딕', sans-serif;
                color: #000;
                line-height: 1.5;
            `;

            const checkedItems = (currentChecklist || []).flatMap(cat => 
                cat.items.filter(item => item.checked).map(item => ({
                    category: cat.category,
                    text: item.text
                }))
            );

            // PDF 내용 생성 - 각 섹션을 식별 가능하게 구조화
            pdfContainer.innerHTML = `
                <!-- Header Section -->
                <div class="pdf-section" style="padding: 20mm 20mm 5mm; background: white; width: 100%; box-sizing: border-box;">
                    <div style="border-bottom: 3px solid #4CAF50; padding-bottom: 12px; margin-bottom: 0;">
                        <h1 style="font-size: 32px; margin: 0; color: #1a202c; letter-spacing: -1px; font-weight: 900;">${schedule.title || '여행 일정'}</h1>
                        <div style="font-size: 15px; margin-top: 12px; color: #4a5568; display: flex; gap: 20px; font-weight: 600;">
                            <span>📅 ${schedule.startDate} ~ ${schedule.endDate}</span>
                            <span>👥 ${schedule.people}인</span>
                            ${displayedTotalCost > 0 ? `
                                <span style="display: flex; align-items: center; gap: 4px; color: #2563eb;">
                                    <span>💰</span> 총 ${displayedTotalCost.toLocaleString()}원
                                </span>
                            ` : ''}
                        </div>
                    </div>
                </div>

                <!-- Checklist Section (Now between title and schedules) -->
                ${checkedItems.length > 0 ? `
                    <div class="pdf-section" style="padding: 5mm 20mm 10mm; background: white; width: 100%; box-sizing: border-box;">
                        <div style="padding: 25px 30px; background: #fffbeb; border: 2px solid #fef3c7; border-radius: 12px;">
                            <h3 style="font-size: 18px; margin: 0 0 15px; color: #92400e; display: flex; align-items: center; font-weight: 900;">
                                <span style="margin-right: 12px; font-size: 20px;">✅</span> 여행 준비물 (체크리스트)
                            </h3>
                            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px;">
                                ${checkedItems.map(item => `
                                    <div style="font-size: 12px; color: #78350f; display: flex; align-items: center; font-weight: 500;">
                                        <span style="margin-right: 8px; color: #d97706; font-size: 13px;">✔</span>
                                        <span style="opacity: 0.6; font-size: 10px; margin-right: 6px; font-weight: 700;">[${item.category}]</span>
                                        <span>${item.text}</span>
                                    </div>
                                `).join('')}
                            </div>
                        </div>
                    </div>
                ` : ''}

                <!-- Content Sections (Days + Items) -->
                ${dailySchedule.length > 0 ? dailySchedule.map(day => `
                    <!-- Day Header -->
                    <div class="pdf-section pdf-day-header" style="padding: 6mm 20mm 3mm; background: white; width: 100%; box-sizing: border-box;">
                        <h2 style="font-size: 24px; margin: 0; color: #1a202c; font-weight: 900; border-bottom: 2px solid #4CAF50; padding-bottom: 10px;">Day ${day.day}</h2>
                    </div>
                    
                    <!-- Items Bundles -->
                    ${day.items.map((item) => `
                        <div class="pdf-section" style="padding: 2.5mm 20mm; background: white; width: 100%; box-sizing: border-box;">
                            <div style="background: #fdfdfd; border-left: 5px solid #4CAF50; border-radius: 4px; padding: 15px 18px; box-shadow: 0 2px 8px rgba(0,0,0,0.02); border: 1px solid #f0f0f0; border-left-width: 5px;">
                                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 6px;">
                                    <div style="display: flex; align-items: center; gap: 10px;">
                                        <span style="font-size: 15px; display: flex; align-items: center;">🕒</span>
                                        <span style="font-size: 16px; font-weight: 800; color: #1a202c;">${item.time}</span>
                                        <span style="color: #cbd5e1; font-weight: 300;">-</span>
                                        <span style="font-size: 16px; display: flex; align-items: center;">${item.emoji}</span>
                                        <span style="font-size: 16px; font-weight: 800; color: #1a202c;">${item.title}</span>
                                    </div>
                                    <div style="display: flex; align-items: center; gap: 6px;">
                                        ${item.cost > 0 ? `
                                            <span style="font-size: 11px; color: #64748b; font-weight: 600; margin-right: 4px;">
                                                ￦${item.cost.toLocaleString()}
                                            </span>
                                        ` : ''}
                                        <span style="background: #e8f5e9; color: #2e7d32; padding: 2px 9px; border-radius: 12px; font-size: 10px; font-weight: 700; letter-spacing: 0.5px;">${item.category || '기타'}</span>
                                    </div>
                                </div>
                                ${item.description ? `
                                    <div style="font-size: 13px; color: #505d6b; line-height: 1.5; margin-left: 28px; font-weight: 500;">
                                        ${item.description}
                                    </div>
                                ` : ''}
                            </div>
                        </div>
                    `).join('')}
                `).join('') : `
                    <!-- Fallback Markdown Block -->
                    <div class="pdf-section" style="padding: 10mm 20mm; background: white; width: 100%; box-sizing: border-box;">
                        <div style="font-size: 16px; color: #333; line-height: 1.8; white-space: pre-wrap; background: #f8fafc; padding: 35px; border-radius: 15px; border: 1px solid #edf2f7; margin-bottom: 20px;">
                            ${schedule.scheduleText ? schedule.scheduleText
                                .replace(/^# (.*$)/gm, '<h1 style="font-size: 24px; margin-top: 30px; margin-bottom: 15px; color: #1a202c; font-weight: 800;">$1</h1>')
                                .replace(/^## (.*$)/gm, '<h2 style="font-size: 20px; margin-top: 25px; margin-bottom: 12px; color: #4a5568; font-weight: 700;">$1</h2>')
                                .replace(/^- (.*$)/gm, '<div style="margin-bottom: 8px;">• $1</div>')
                                .replace(/\n/g, '<br/>') : '일정 내용이 없습니다.'}
                        </div>
                    </div>
                `}

                <!-- Footer Section -->
                <div class="pdf-section" style="padding: 15mm 20mm 20mm; background: white; width: 100%; box-sizing: border-box; text-align: center;">
                    <div style="border-top: 1px solid #f1f5f9; padding-top: 40px;">
                        <p style="font-size: 16px; color: #64748b; font-style: italic; font-weight: 600; letter-spacing: 0.5px;">Walk your path, Fly your dream — Walk2Fly ✈️</p>
                        <p style="font-size: 11px; color: #94a3b8; margin-top: 10px; font-weight: 400;">Created with AI Trip Assistant • ${new Date().toLocaleDateString()}</p>
                    </div>
                </div>
            `;

            document.body.appendChild(pdfContainer);

            // PDF 초기화
            const pdf = new jsPDF({
                orientation: 'portrait',
                unit: 'mm',
                format: 'a4',
                compress: true
            });

            const pdfWidth = 210;
            const pdfHeight = 297;
            const topBottomMargin = 15; // mm
            let currentY = topBottomMargin;

            const sections = pdfContainer.querySelectorAll('.pdf-section');
            
            for (let i = 0; i < sections.length; i++) {
                const section = sections[i];
                const canvas = await html2canvas(section, {
                    scale: 3, // Higher scale for ultra-sharp text
                    useCORS: true,
                    backgroundColor: '#ffffff',
                    logging: false,
                    onclone: (clonedDoc) => {
                        // Ensure invisible elements don't interfere
                        const el = clonedDoc.querySelector('.pdf-section');
                        if (el) el.style.boxShadow = 'none';
                    }
                });

                const imgData = canvas.toDataURL('image/jpeg', 0.95);
                const imgWidth = pdfWidth;
                const imgHeight = (canvas.height * imgWidth) / canvas.width;

                // Day Header인 경우, 최소 한 개 이상의 아이템이 들어갈 공간이 있는지 확인 (약 50mm)
                const isDayHeader = section.classList.contains('pdf-day-header');
                const checkHeight = isDayHeader ? imgHeight + 50 : imgHeight;

                // 만약 현재 페이지에 공간이 부족하면 새 페이지 추가
                // 단, 섹션 하나가 페이지 전체보다 크면 어쩔 수 없이 잘려야 함 (그런 경우는 보통 없음)
                if (currentY + checkHeight > pdfHeight - topBottomMargin && currentY > topBottomMargin) {
                    pdf.addPage();
                    currentY = topBottomMargin;
                }

                pdf.addImage(imgData, 'JPEG', 0, currentY, imgWidth, imgHeight, undefined, 'FAST');
                currentY += imgHeight;
            }

            document.body.removeChild(pdfContainer);

            // PDF를 Blob으로 생성
            const pdfBlob = pdf.output('blob');
            const pdfUrl = URL.createObjectURL(pdfBlob);
            const fileName = `${schedule.title || "여행일정"}_일정표.pdf`;

            // PDF 다운로드
            const link = document.createElement('a');
            link.href = pdfUrl;
            link.download = fileName;
            link.click();

            // 성공 토스트 (파일 열기/공유하기 버튼 포함)
            toast.success(
                (t) => (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                        <div style={{ fontWeight: 600 }}>✅ PDF 저장 완료!</div>
                        <div style={{ display: 'flex', gap: '8px' }}>
                            <button
                                onClick={() => {
                                    window.open(pdfUrl, '_blank');
                                    toast.dismiss(t.id);
                                }}
                                style={{
                                    padding: '8px 16px',
                                    borderRadius: '6px',
                                    border: '1px solid #66bb6a',
                                    background: '#66bb6a',
                                    color: 'white',
                                    fontWeight: 600,
                                    cursor: 'pointer',
                                    fontSize: '13px'
                                }}
                            >
                                📄 파일 열기
                            </button>
                            <button
                                onClick={async () => {
                                    try {
                                        if (navigator.share && navigator.canShare && navigator.canShare({ files: [new File([], 'test.pdf')] })) {
                                            // Web Share API 지원 (모바일)
                                            const file = new File([pdfBlob], fileName, { type: 'application/pdf' });
                                            await navigator.share({
                                                files: [file],
                                                title: schedule.title || '여행 일정',
                                                text: '여행 일정표를 공유합니다'
                                            });
                                        } else {
                                            // 데스크톱: 이메일로 공유
                                            const emailSubject = encodeURIComponent(`${schedule.title || '여행 일정'} - 일정표`);
                                            const emailBody = encodeURIComponent(
                                                `${schedule.title || '여행 일정'} 일정표를 첨부합니다.\n\n` +
                                                `기간: ${schedule.startDate} ~ ${schedule.endDate}\n` +
                                                `인원: ${schedule.people}명\n\n` +
                                                `※ 다운로드된 PDF 파일을 이메일에 첨부해주세요.`
                                            );

                                            // 이메일 클라이언트 열기
                                            window.location.href = `mailto:?subject=${emailSubject}&body=${emailBody}`;

                                            toast.success('이메일 앱이 열립니다. 다운로드된 PDF를 첨부해주세요!', {
                                                duration: 5000
                                            });
                                        }
                                    } catch (err) {
                                        if (err.name !== 'AbortError') {
                                            console.error('공유 실패:', err);
                                        }
                                    }
                                    toast.dismiss(t.id);
                                }}
                                style={{
                                    padding: '8px 16px',
                                    borderRadius: '6px',
                                    border: '1px solid rgba(102, 187, 106, 0.3)',
                                    background: 'transparent',
                                    color: '#66bb6a',
                                    fontWeight: 600,
                                    cursor: 'pointer',
                                    fontSize: '13px'
                                }}
                            >
                                🔗 공유하기
                            </button>
                        </div>
                    </div>
                ),
                {
                    id: toastId,
                    duration: 10000, // 10초 동안 표시
                    style: {
                        minWidth: '300px'
                    }
                }
            );

            // 10초 후 blob URL 해제
            setTimeout(() => {
                URL.revokeObjectURL(pdfUrl);
            }, 10000);
        } catch (error) {
            console.error("PDF 생성 실패:", error);
            toast.error("PDF 생성에 실패했습니다.", { id: toastId });
        } finally {
            setIsGeneratingPDF(false);
        }
    };



    // 커뮤니티 공유 함수 - 모달 트리거로 변경
    const triggerShareConfirm = () => {
        if (!user) {
            toast.error("로그인이 필요한 기능입니다.");
            return;
        }
        setShowShareConfirm(true);
    };

    // 마크다운/JSON 형식 제거 및 요약 함수
    // 커뮤니티 공유용 일정 포맷터 (상세 내용 포함)
    const formatScheduleForShare = (text) => {
        if (!text) return "";
        try {
            const parsed = JSON.parse(text);
            if (Array.isArray(parsed)) {
                return parsed.map(day => {
                    const dateHeader = `[Day ${day.day}]`;
                    const items = (day.spots || day.items || []).map(s => {
                        const time = s.time || "00:00";
                        const title = s.spot || s.title || "장소";
                         const cost = s.cost ? ` (${s.cost.toLocaleString()}원)` : "";
                        return `  • ${time} ${s.emoji || ''} ${title}${cost} - ${s.activity || s.description || ''}`;
                    }).join('\n');
                    return `${dateHeader}\n${items}`;
                }).join('\n\n');
            }
        } catch (e) {
            // JSON 파싱 실패 시 일반 텍스트 처리 (기본 마크다운 제거)
        }

        return text
            .replace(/^#+ /gm, '')
            .replace(/\*\*(.*?)\*\*/g, '$1')
            .replace(/^- /gm, '• ')
            .replace(/\[Day (\d+)\]/g, '\n[Day $1]')
            .trim();
    };

    const handleShareToCommunity = async () => {
        if (isSharing) return;
        setIsSharing(true);
        setShowShareConfirm(false);
        const loadingToast = toast.loading("커뮤니티로 여행기를 보내고 있어요...");
        try {
            const formattedSchedule = formatScheduleForShare(schedule.scheduleText);
            const totalCostStr = displayedTotalCost > 0 ? `\n💰 총 예상 비용: ${displayedTotalCost.toLocaleString()}원\n` : "";

            const postData = {
                user_id: user.id,
                category: 'free',
                title: `✨ 추천 여행: ${schedule.title}`,
                content: `안녕하세요! 제가 계획한 여행 일정을 공유합니다.\n\n📍 여행지: ${schedule.title}\n📅 기간: ${schedule.startDate} ~ ${schedule.endDate}\n👥 인원: ${schedule.people}명${totalCostStr}\n\n--- 상세 일정 ---\n${formattedSchedule}`,
                theme: 'healing'
            };

            const { data, error } = await communityService.createPost(postData);
            if (error) throw error;

            toast.success("자유게시판에 성공적으로 공유되었습니다!", { id: loadingToast });
            setShowShareSuccess(true);
        } catch (error) {
            console.error("Share error:", error);
            toast.error("공유에 실패했습니다.", { id: loadingToast });
        } finally {
            setIsSharing(false);
        }
    };

    const dailySchedule = parseDailySchedule(schedule.scheduleText);

    if (dailySchedule.length === 0 && !schedule.scheduleText) {
        return (
            <div className="scheduleDetailEmpty">
                <p className="emptyText">작성된 일정이 없습니다.</p>
            </div>
        );
    }

    const currentDayData = dailySchedule.length > 0 ? (dailySchedule.find(d => d.day === activeDay) || dailySchedule[0]) : null;

    const displayedTotalCost = schedule.totalCost || dailySchedule.reduce((sum, day) => 
        sum + day.items.reduce((dSum, item) => dSum + (item.cost || 0), 0), 0
    );

    return (
        <>
            <div className="scheduleDetailTimeline">
                <div className="timelineHeader">
                    <div className="timelineHeaderLeft">
                        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                            <h3>여행 일정</h3>
                            {displayedTotalCost > 0 && (
                                <div style={{
                                    display: 'flex',
                                    alignItems: 'center',
                                    gap: '6px',
                                    padding: '6px 14px',
                                    background: '#eff6ff',
                                    borderRadius: '20px',
                                    color: '#2563eb',
                                    fontSize: '0.9rem',
                                    fontWeight: '700',
                                    boxShadow: '0 2px 4px rgba(37,99,235,0.1)'
                                }}>
                                    <span>💰</span>
                                    <span>총 {displayedTotalCost.toLocaleString()}원</span>
                                </div>
                            )}
                        </div>
                        <div className="timelineInfo">
                            <span>📅 {schedule.startDate} ~ {schedule.endDate}</span>
                            <span>👥 {schedule.people}인</span>
                        </div>
                    </div>

                    {/* PDF 저장 버튼 */}
                    <button
                        className="pdfSaveBtn"
                        onClick={generatePDF}
                        disabled={isGeneratingPDF}
                    >
                        <div className="pdfIcon">📄</div>
                        <div className="pdfText">
                            <div className="pdfTitle">여행 계획을 PDF로 저장해요</div>
                            <div className="pdfDesc">프린트하거나 공유하기 편해요</div>
                        </div>
                    </button>

                    {/* 커뮤니티 공유 버튼 */}
                    <button
                        className="pdfSaveBtn"
                        onClick={triggerShareConfirm}
                        style={{ 
                            marginLeft: '12px', 
                            background: 'linear-gradient(135deg, #3b82f6, #2563eb)',
                            border: 'none',
                            color: 'white'
                        }}
                    >
                        <div className="pdfIcon">🌍</div>
                        <div className="pdfText">
                            <div className="pdfTitle" style={{ color: 'white' }}>커뮤니티에 공유하기</div>
                            <div className="pdfDesc" style={{ color: 'rgba(255,255,255,0.8)' }}>자유게시판에 일정을 자랑해보세요</div>
                        </div>
                    </button>
                </div>

                {/* Section Navigation */}
                <div className="sectionNav">
                    <button
                        className={activeSection === "timeline" ? "sectionBtn active" : "sectionBtn"}
                        onClick={() => setActiveSection("timeline")}
                    >
                        📅 타임라인
                    </button>
                    <button
                        className={activeSection === "checklist" ? "sectionBtn active" : "sectionBtn"}
                        onClick={() => setActiveSection("checklist")}
                    >
                        ✅ 체크리스트
                    </button>
                    <button
                        className={activeSection === "tips" ? "sectionBtn active" : "sectionBtn"}
                        onClick={() => setActiveSection("tips")}
                    >
                        💡 여행 팁
                    </button>
                </div>

                {/* Timeline Section */}
                {activeSection === "timeline" && (
                    <>
                        {/* Day Tabs - Only show if we have parsed days */}
                        {dailySchedule.length > 0 ? (
                            <>
                                {dailySchedule.length > 1 && (
                                    <div className="dayTabs">
                                        {dailySchedule.map((dayData) => (
                                            <button
                                                key={dayData.day}
                                                className={`dayTab ${activeDay === dayData.day ? 'active' : ''}`}
                                                onClick={() => setActiveDay(dayData.day)}
                                            >
                                                Day {dayData.day}
                                            </button>
                                        ))}
                                    </div>
                                )}

                                <div className="timelineItems">
                                    {currentDayData?.items.map((item, index) => (
                                        <div key={index} className="timelineItem">
                                            <div className="timelineDot">
                                                <div className="dot"></div>
                                                {index < currentDayData.items.length - 1 && (
                                                    <div className="connector"></div>
                                                )}
                                            </div>

                                            <div className="timelineContent">
                                                <div className="timelineTime">
                                                    <span className="timeIcon">🕐</span>
                                                    <span className="timeText">{item.time}</span>
                                                </div>

                                                <div className="timelineCard">
                                                    <div className="cardHeader">
                                                        <div className="cardTitle">
                                                            <span className="cardEmoji">{item.emoji}</span>
                                                            <span className="cardTitleText">{item.title}</span>
                                                        </div>
                                                        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end' }}>
                                                            <span className="cardCategory">{item.category}</span>
                                                            {item.cost > 0 && (
                                                                <span className="itemCost" style={{ fontSize: '0.8rem', color: '#64748b', marginTop: '4px', fontWeight: '500' }}>
                                                                    {item.cost.toLocaleString()}원
                                                                </span>
                                                            )}
                                                        </div>
                                                    </div>

                                                    {item.description && (
                                                        <div className="cardBody">
                                                            <p className={`cardDescription ${expandedItems[`${activeDay}-${index}`] ? 'expanded' : ''}`}>
                                                                {item.description}
                                                            </p>
                                                            {item.description.length > 50 && (
                                                                <button
                                                                    className="expandBtn"
                                                                    onClick={() => toggleExpand(activeDay, index)}
                                                                >
                                                                    {expandedItems[`${activeDay}-${index}`] ? '간략히 보기' : '자세한 보기'}
                                                                </button>
                                                            )}
                                                        </div>
                                                    )}
                                                </div>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </>
                        ) : (
                            /* Fallback for Freeform Markdown Text */
                            <div className="markdown-schedule-view" style={{ 
                                padding: '24px', 
                                background: '#fff', 
                                borderRadius: '16px', 
                                boxShadow: '0 4px 20px rgba(0,0,0,0.05)',
                                fontSize: '1rem',
                                lineHeight: '1.7',
                                color: '#333'
                            }}>
                                <ReactMarkdown 
                                    components={{
                                        h1: ({node, ...props}) => <h1 style={{fontSize: '1.5rem', borderBottom: '2px solid #f3f4f6', paddingBottom: '10px', marginTop: '10px', marginBottom: '20px'}} {...props} />,
                                        h2: ({node, ...props}) => <h2 style={{fontSize: '1.3rem', color: '#2563eb', marginTop: '24px', marginBottom: '16px'}} {...props} />,
                                        li: ({node, ...props}) => <li style={{marginBottom: '8px'}} {...props} />,
                                        blockquote: ({node, ...props}) => <blockquote style={{borderLeft: '4px solid #e5e7eb', paddingLeft: '16px', color: '#6b7280', margin: '16px 0'}} {...props} />
                                    }}
                                >
                                    {schedule.scheduleText}
                                </ReactMarkdown>
                            </div>
                        )}
                    </>
                )}

                {/* Checklist Section - Always mount but hide if not active to ensure data sync for PDF */}
                <div className="sectionContent" style={{ display: activeSection === "checklist" ? "block" : "none" }}>
                    <TravelChecklist 
                        key={`checklist-${schedule.id}-${user?.id || 'guest'}`}
                        destination={schedule.title} 
                        scheduleId={schedule.id} 
                        onChange={handleChecklistChange}
                    />
                </div>

                {/* Tips Section */}
                {activeSection === "tips" && (
                    <div className="sectionContent">
                        <TravelTips />
                    </div>
                )}
            </div>

            {/* --- MZ Style Custom Modals --- */}
            <AnimatePresence>
                {/* 1. 공유 확인 모달 */}
                {showShareConfirm && (
                    <motion.div 
                        className="modal-overlay"
                        initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                        style={{ 
                            zIndex: 2000, 
                            background: 'rgba(0,0,0,0.4)', 
                            backdropFilter: 'blur(8px)',
                            position: 'fixed',
                            top: 0,
                            left: 0,
                            right: 0,
                            bottom: 0,
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center'
                        }}
                        onClick={() => setShowShareConfirm(false)}
                    >
                        <motion.div 
                            className="mz-modal"
                            initial={{ scale: 0.9, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: 0.9, y: 20 }}
                            onClick={e => e.stopPropagation()}
                            style={{
                                background: 'white',
                                padding: '30px',
                                borderRadius: '30px',
                                width: '90%',
                                maxWidth: '400px',
                                textAlign: 'center',
                                boxShadow: '0 20px 40px rgba(0,0,0,0.1)'
                            }}
                        >
                            <div style={{ fontSize: '3rem', marginBottom: '20px' }}>🌍</div>
                            <h3 style={{ fontSize: '1.4rem', fontWeight: 800, marginBottom: '12px', color: '#111' }}>커뮤니티에 자랑할까요?</h3>
                            <p style={{ color: '#666', lineHeight: 1.6, marginBottom: '24px' }}>
                                방금 만든 멋진 일정을 <br/> 
                                <strong>자유게시판</strong>에 공유하고 칭찬받아보세요!
                            </p>
                            <div style={{ display: 'flex', gap: '12px' }}>
                                <button 
                                    onClick={() => setShowShareConfirm(false)}
                                    style={{
                                        flex: 1,
                                        padding: '14px',
                                        borderRadius: '16px',
                                        border: 'none',
                                        background: '#f3f4f6',
                                        color: '#4b5563',
                                        fontWeight: 700,
                                        cursor: 'pointer'
                                    }}
                                >나중에</button>
                                <button 
                                    onClick={handleShareToCommunity}
                                    disabled={isSharing}
                                    style={{
                                        flex: 1,
                                        padding: '14px',
                                        borderRadius: '16px',
                                        border: 'none',
                                        background: isSharing ? '#9ca3af' : 'linear-gradient(135deg, #3b82f6, #2563eb)',
                                        color: 'white',
                                        fontWeight: 700,
                                        cursor: isSharing ? 'not-allowed' : 'pointer',
                                        boxShadow: isSharing ? 'none' : '0 4px 12px rgba(59,130,246,0.3)',
                                        transition: 'all 0.2s'
                                    }}
                                >
                                    {isSharing ? '보내고 있어요...' : '지금 바로!'}
                                </button>
                            </div>
                        </motion.div>
                    </motion.div>
                )}

                {/* 2. 공유 완료 모달 */}
                {showShareSuccess && (
                    <motion.div 
                        className="modal-overlay"
                        initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                        style={{ 
                            zIndex: 2000, 
                            background: 'rgba(0,0,0,0.4)', 
                            backdropFilter: 'blur(8px)',
                            position: 'fixed',
                            top: 0,
                            left: 0,
                            right: 0,
                            bottom: 0,
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center'
                        }}
                        onClick={() => setShowShareSuccess(false)}
                    >
                        <motion.div 
                            className="mz-modal"
                            initial={{ scale: 0.9, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: 0.9, y: 20 }}
                            onClick={e => e.stopPropagation()}
                            style={{
                                background: 'white',
                                padding: '30px',
                                borderRadius: '30px',
                                width: '90%',
                                maxWidth: '400px',
                                textAlign: 'center',
                                boxShadow: '0 20px 40px rgba(0,0,0,0.1)'
                            }}
                        >
                            <div style={{ fontSize: '3.5rem', marginBottom: '20px' }}>🚀</div>
                            <h3 style={{ fontSize: '1.4rem', fontWeight: 800, marginBottom: '12px', color: '#111' }}>공유 완료!</h3>
                            <p style={{ color: '#666', lineHeight: 1.6, marginBottom: '24px' }}>
                                일정이 지구 반대편(?)까지 전송되었습니다. <br/>
                                지금 바로 커뮤니티에서 확인해보세요!
                            </p>
                            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                                <button 
                                    onClick={() => {
                                        setShowShareSuccess(false);
                                        navigate('/community');
                                    }}
                                    style={{
                                        width: '100%',
                                        padding: '14px',
                                        borderRadius: '16px',
                                        border: 'none',
                                        background: '#10b981',
                                        color: 'white',
                                        fontWeight: 700,
                                        cursor: 'pointer'
                                    }}
                                >게시글 보러가기</button>
                                <button 
                                    onClick={() => setShowShareSuccess(false)}
                                    style={{
                                        width: '100%',
                                        padding: '14px',
                                        borderRadius: '16px',
                                        border: 'none',
                                        background: 'transparent',
                                        color: '#9ca3af',
                                        fontWeight: 600,
                                        cursor: 'pointer'
                                    }}
                                >창 닫기</button>
                            </div>
                        </motion.div>
                    </motion.div>
                )}
            </AnimatePresence>
        </>
    );
}
